import { actions } from "./index";

export const {
  OPEN_CREATOR,
  CLOSE_CREATOR_FE,
  OPEN_EDITOR,
  CLOSE_EDITOR,
  EDIT_QUESTION,
  CHOOSE_ANSWER_CORRECT,
  WARN_NO_TEXT,
  STOP_WARNING,
  EDIT_ANSWER,
  DELETING_ANSWER,
  DELETED_ANSWER,
  ADDED_ANSWER,
  TOGGLE_MULTI_CORRECT_ANSWERS,
  CHANGE_TIME_LIMIT,
  SAVE_QUEST_FE,
  EDIT_QUEST,
  DUPLICATE_QUEST,
  DELETE_QUEST_FE,
} = actions;
